### ISSUE TITLE
Create multiple templates for landing pages

### ISSUE THREAD

**Issue by websquared** [websquared/lfc#53] opened 2018-07-03 19:46 UTC
_From @websquared on May 29, 2018 12:57_

We need to create multiple templates for account manager to choose and create their own landing page - for leads generation or different call-to-actions.

The idea is that a Manager can select one of our templates to create a page and then modify texts and images using JS - by clicking on different page sections.

@kurumbus @polis89 Let's have a Skype call so I can explain the details.

Here are some of the templates that we like. We don't need all of them at the beginning. Maybe with 4-5 for now. And then keep adding new ones.

Lead Generation:
- [x] https://instapage.com/landing-page-templates/carelife
- [x] https://instapage.com/landing-page-templates/newsity-lead

Two-Step:
- [x] https://instapage.com/landing-page-templates/helptech-two-step
- [x] https://instapage.com/landing-page-templates/liveweb

Click-Through:
- [x] https://instapage.com/landing-page-templates/bookshelf
- [x] https://instapage.com/landing-page-templates/topinvest-thanks

Thank You:
- [x] https://instapage.com/landing-page-templates/10blokks-thanks
- [x] https://instapage.com/landing-page-templates/webinar-thanks

Webinar:
- [x] https://instapage.com/landing-page-templates/webvent
- [x] https://instapage.com/landing-page-templates/webinare

E-Book:
- [x] https://instapage.com/landing-page-templates/probook
- [x] https://instapage.com/landing-page-templates/business-ebook

Event:
- [x] https://instapage.com/landing-page-templates/stravent-two-step
- [x] https://instapage.com/landing-page-templates/confcon-event

App:
- [x] https://instapage.com/landing-page-templates/seshapp
- [x] https://instapage.com/landing-page-templates/snapapp

_Copied from original issue: websquared/learnformula-cloud#155_

**Comment by websquared** [comment] 2018-07-03 19:46
@kurumbus 
Please fee free to start working on this task - we have a few templates created by @polis89:
/resources/views/accounts/leads/templates/

**Comment by websquared** [comment] 2018-07-03 19:46
@kurumbus Could you please explain to me how it works?
Maybe record a short screen-cast video for any new feature?

**Comment by websquared** [comment] 2018-07-03 19:46
_From @kurumbus on June 8, 2018 17:22_

Ok, will do

**Comment by websquared** [comment] 2018-07-03 19:46
_From @polis89 on June 9, 2018 11:56_

@kurumbus After last merge i cannot open templates on links like this: 'http://acme.learnformula.test/accounts/leads/templates/carelife', im logged in. How can i watch it?

**Comment by kurumbus** [comment] 2018-07-03 22:45
@websquared @polis89

Let me check

**Comment by kurumbus** [comment] 2018-07-03 22:53
@websquared Well, this route is for managers only, I guess it's a feature, not a bug, right? 

Although that particular template doesn't have defaults (I didn't yet get to it, we have only two templates ready), so it can be previewed like this:
http://acme.learnformula.test/tmp/carelife

I should say it was like this all the way, I think

**Comment by websquared** [comment] 2018-07-12 19:10
@polis89 We need all the 14 templates now. Gregory told me that we don't have all of them. Could you mark that you already did and finish others?
Thanks.

**Comment by websquared** [comment] 2018-07-12 19:10
Related to #52

**Comment by kurumbus** [comment] 2018-07-24 23:13
- [ ] Preselect in index

**Comment by kurumbus** [comment] 2018-07-27 16:04
@Alinlish Could you please test this functionality? (Dmitriy approved)

**Comment by Alinlish** [comment] 2018-07-28 10:57
My comments:
1. When accessing one landing page with preview, then complete one email (or leave the field empty) and click on Get you ebook [Link](https://www.screencast.com/t/Cd4hr2Ysqc), if the user is clicking on return for few times, previous page is not displayed [Link](https://www.screencast.com/t/OiUcBwGCtW7n)
2. Cannot edit text from a button in a landing page, but it looks editable [Link](https://www.screencast.com/t/pLkoDefnz)
3. If clicking on Edit button for a landing page from "Landing pages" [Link](https://www.screencast.com/t/UC4xMMMv), , after clicking Return back, the "Setting" page is opened, not "Landing pages" [Link](https://www.screencast.com/t/nF9mpxLjhM7)
4. On a page to create a new Landing page, if clicking on View template button [Link](https://www.screencast.com/t/VOYxyFL3319), the first template is opened, not the template selected in dropdown before View template button [Link](https://www.screencast.com/t/SadBkqqKA)
5. There are two parenthesis after "Following List" when submitting a new landing page [Link](https://www.screencast.com/t/LGrE2hRe)
6. When creating a list, the field Copy Metadata from is always loading [Link](https://www.screencast.com/t/HVvV35C4sX0w)
7. When creating a new list, page is continuously loading [Link](https://www.screencast.com/t/19AH7Ca8d2FW)
8. Wehn creating a new landing page, if adding an external resource, after clicking on Submit the link field [Link](https://www.screencast.com/t/yhJNg7ltL) is copied on the Lead Page Title [Link](https://www.screencast.com/t/tEHy8nZ7)
9. The message to complete lead page title remains displayed after clicking on create [Link1](https://www.screencast.com/t/rpnm2bfOwM) [Link2](https://www.screencast.com/t/3NVCFpDuzP)
10. When clicking on Add resources with Lead Page title completed, if no resource is added, after clicking on Submit, the Lead Page title becomes empty [Link](https://www.screencast.com/t/I1cIHQrzFIAo)
11. When buying many templates, on second page at Landing pages, the option to move through pages is not at bottom, as it should [Link](https://www.screencast.com/t/fSQQmesaLCuQ)
12. No message displayed if subscribing on all landing pages (on upper side or on bottom side). Basically nothing happens when I complete my email and click on Submit. From around 30 places to submit, maximum 5 have messages added. [Link](https://www.screencast.com/t/w3vPns5DXGo).
13. No email is received on inbox when subscribing to any landing page [Link](https://www.screencast.com/t/w3vPns5DXGo)
14. No email is sent when using the option "Send a letter" [Link](https://www.screencast.com/t/DioT6soWV8C)
15. For Leads, filter can be applied on name, but the name is not completed when subscribing to any landing page [Link](https://www.screencast.com/t/OmUOU51vN)
16. For Leads, if setting one filter [Link](https://www.screencast.com/t/4zupEwEt07K4) and going on second page, the filter is removed. The same on Landing pages.
17. As a proposal, it would be good to join together all options related to landing page on menu (Landing page templates, Landing pages and Leads). If possible, add one title Landing page, and subtitles templates, pages and leads [Link](https://www.screencast.com/t/YzwGvRQnp). On Settings page, those option are together [Link](https://www.screencast.com/t/JpfgWpnb)
18. On Landing pages, at filters, if selecting subscribers and ascending, the arrows are moving down [Link](https://www.screencast.com/t/AQOL3ZauedD)
19. On Leads page, when clicking on Import Leads and leaving file field empty [Link](https://www.screencast.com/t/by77XLSp), when clicking on Save, the successful message is displayed [Link](https://www.screencast.com/t/G1t741ek)
20. On Leads page, when clicking on Add Lead, leaving all fields empty (or with wrong data completed) and saving, the error message is displayed but the page is continuously loading [Link](https://www.screencast.com/t/SorvNINFg)
21. When adding a new lead from button Add Lead, the numbers completed [Link](https://www.screencast.com/t/Lh7429bDAM1) are not displayed on table [Link](https://www.screencast.com/t/ZtwUqrzZXA)

**Comment by kurumbus** [comment] 2018-07-28 22:07
@Alinlish thank you!

**Comment by kurumbus** [comment] 2018-07-31 19:50
@websquared I turn to fixing this one now

**Comment by websquared** [comment] 2018-07-31 20:14
@kurumbus Please note that I've made some UI changes - I hope it didn't break any of the functionality

**Comment by kurumbus** [comment] 2018-07-31 21:01
@websquared I've noticed changes, but can't see any problems yet. Hope there will be none, but if there are, I'll deal with them.

**Comment by kurumbus** [comment] 2018-07-31 21:40
- [X] 5 There are two parenthesis after "Following List" when submitting a new landing page
- [X] 4 On a page to create a new Landing page, if clicking on View template button Link, the first template is opened, not the template selected in dropdown before View template button 
- [X] 11 When buying many templates, on second page at Landing pages, the option to move through pages is not at bottom, as it should

**Comment by kurumbus** [comment] 2018-07-31 21:56
- [X] 14 No email is sent when using the option "Send a letter"
- [X] 16 For Leads, if setting one filter Link and going on second page, the filter is removed. The same on Landing pages.

**Comment by kurumbus** [comment] 2018-07-31 22:13
- [X] 18 On Landing pages, at filters, if selecting subscribers and ascending, the arrows are moving down
- [X] 19 On Leads page, when clicking on Import Leads and leaving file field empty Link, when clicking on Save, the successful message is displayed

**Comment by kurumbus** [comment] 2018-08-01 21:09
@websquared Each lead has status and type integer fields. When we added this functionality, we decided to think about concrete types and statuses later. I think the time has come. 

I propose the following, but you should edit it since it's mainly a business question.
statuses: new, working, converted, declined
types: imported, subscribed.

**Comment by kurumbus** [comment] 2018-08-01 21:13
- [X] 20 On Leads page, when clicking on Add Lead, leaving all fields empty (or with wrong data completed) and saving, the error message is displayed but the page is continuously loading 
- [X] 21 When adding a new lead from button Add Lead, the numbers completed Link are not displayed on table

**Comment by kurumbus** [comment] 2018-08-01 21:17
- [X] 13 No email is received on inbox when subscribing to any landing page Link

**Comment by kurumbus** [comment] 2018-08-01 21:32
- [X]  10 When clicking on Add resources with Lead Page title completed, if no resource is added, after clicking on Submit, the Lead Page title becomes empty Link ( @Alinlish I guess it was hard to spot this one :-) )

**Comment by kurumbus** [comment] 2018-08-01 21:38
- [X] When creating a new landing page if adding an external resource, after clicking on Submit the link field Link is copied on the Lead Page Title Link

**Comment by websquared** [comment] 2018-08-02 13:41
@kurumbus regarding lead statuses:
We don't really want to create full Marketing Automation Software - at least for now. So we only need to capture leads and then sync to their Marketing Software - they should handle their statuses there.
However we might need some column or type "imported" as you suggested - for our cron to know which ones are already imported.

**Comment by kurumbus** [comment] 2018-08-02 17:10
@websquared Ok. 
It's not that I wanted to create something complex, it's just now "add lead" table looks like this: 

![Uploading 2018-08-02 (1).png…]()

And it's really stupid to let people assign integer types. So I'll make type assigned automatically on whether lead is subscribed or imported and hide status for now, OK?

**Comment by websquared** [comment] 2018-08-02 17:37
Sure, sounds good

**Comment by kurumbus** [comment] 2018-08-02 18:28
- [X] 15 For Leads, filter can be applied on name, but the name is not completed when subscribing to any landing page Link

- Well, that's how it is, but I added ability to edit leads and thus add first name and last name

**Comment by kurumbus** [comment] 2018-08-02 21:35
- [X] 1 When accessing one landing page with preview, then complete one email (or leave the field empty) and click on Get you ebook Link, if the user is clicking on return for few times, previous page is not displayed 
- [X] 3 If clicking on Edit button for a landing page from "Landing pages" Link, , after clicking Return back, the "Setting" page is opened, not "Landing pages"

**Comment by kurumbus** [comment] 2018-08-02 21:40
What's left:
- [ ] 2 Cannot edit text from a button in a landing page, but it looks editable Link
- [ ] 6 When creating a list, the field Copy Metadata from is always loading Link
- [ ] 7  When creating a new list, page is continuously loading Link
- [ ] 9 The message to complete lead page title remains displayed after clicking on create
- [ ] 12 No message displayed if subscribing on all landing pages (on upper side or on bottom side). Basically nothing happens when I complete my email and click on Submit. From around 30 places to submit, maximum 5 have messages added.  
- [ ] 17 As a proposal, it would be good to join together all options related to landing page on menu (Landing page templates, Landing pages and Leads). If possible, add one title Landing page, and subtitles templates, pages and leads Link. On Settings page, those option are together

**Comment by kurumbus** [comment] 2018-08-08 15:44
@websquared returning to the remaining points of this one.

**Comment by kurumbus** [comment] 2018-08-09 15:50
@websquared could you please tell, can you reproduce points 2, 6 and 7? Because I can't, perhaps that's because we didn't have API key check in the past.

Otherwise, done here.

**Comment by kurumbus** [comment] 2018-08-11 12:25
@Alinlish Could you test this one also if you have the opportunity?

**Comment by Alinlish** [comment] 2018-08-12 18:56
My comments:
- Solved: 1, 4, 5, 8, 10, 11, 14, 15, 16, 18, 20, 21,
- Not solved: 2, 3, 6, 7, 9, 12, 13, 17, 19 (the error message is wrong [Link](https://www.screencast.com/t/ABcgf2QMi4) and page is continuously loading),

**Comment by kurumbus** [comment] 2018-09-03 17:48
- [X]  9 The message to complete lead page title remains displayed after clicking on create (found second place for this bug)
- [X] 19 On Leads page, when clicking on Import Leads and leaving file field empty Link, when clicking on Save, the successful message is displayed

**Comment by kurumbus** [comment] 2018-09-03 18:11
I couldn't reproduce some of the stuff and fixed the others. So will close this for now.

**Closed by kurumbus** 2018-09-03 18:11 UTC
Labels: URGENT, feature
